### ISSUE TITLE
can you offer 'QueryInst_Swin_L_300_queries (single scale testing)' config

### ISSUE THREAD

**Issue by silencesuper** [hustvl/QueryInst#1]
thank you.

**Comment by vealocia** [comment]
> thank you.

@silencesuper We just released the configuration and source code for QueryInst with Swin Transformer.

**Comment by silencesuper** [comment]
> > thank you.
> 
> @silencesuper We just released the configuration and source code for QueryInst with Swin Transformer.

**Comment by silencesuper** [comment]
many thanks...
