### ISSUE TITLE
Training Memory Usage

### ISSUE THREAD

**Issue by shikunyu8** [hustvl/QueryInst#10]
Thanks for sharing the implementation!

I got memory error with this config `https://github.com/hustvl/QueryInst/blob/main/configs/queryinst/queryinst_swin_large_patch4_window7_fpn_300_proposals_crop_mstrain_400-1200_50e_coco.py`. I used 8 GPUs each with 32 GB memeory.

What GPUs did you use to conduct your experiments?

![image](https://user-images.githubusercontent.com/30034854/120869463-63a66380-c54b-11eb-8fc6-e2cc17f78405.png)

**Comment by vealocia** [comment]
For swin-transformer backbone, we follow the official implementation and use ```torch.checkpoint``` for memory reduction. Please use the following commands:
```
./tools/dist_train.sh configs/queryinst/queryinst_swin_large_patch4_window7_fpn_300_proposals_crop_mstrain_400-1200_50e_coco.py 8 --cfg-options model.pretrained=<PRETRAIN_MODEL>model.backbone.use_checkpoint=True
```
```pretrain model``` can be found [here](https://github.com/microsoft/Swin-Transformer)
Hope this helps!

**Comment by shikunyu8** [comment]
Oh, I see. Thanks for reply!
I'm closing this issue.
