### ISSUE TITLE
Code on Youtube-VIS

### ISSUE THREAD

**Issue by JialianW** [hustvl/QueryInst#11]
Hi there authors,

Thank you for your great open-source work! May I know when you are going to release the code on Youtube-VIS dataset? And BTW what is the image resolutions you are using for Youtube-VIS dataset?

Thanks and look forward to your reply!

**Comment by Yuxin-CV** [comment]
Hi @JialianW, thanks for your interest in our work!

We will release the VIS part code in a month, please stay tuned :)

The input resolution is 360x640, the multi-scale setting follows SipMask.

**Comment by YimingCuiCuiCui** [comment]
Thank you for your great work. Since it's the end of July, I wonder when will you release the VIS part code? Thank you!
