### ISSUE TITLE
CUDA OOM on 2080Ti

### ISSUE THREAD

**Issue by talent-less** [hustvl/QueryInst#14]
I tired `queryinst_r50_fpn_100_proposals_mstrain_480-800_3x_coc` `queryinst_r101_fpn_300_proposals_crop_mstrain_480-800_` with batchsize=1, but both of them end up with OOM in like half an hour after starting. 

There seems to be a memory leak somewhere.

**Comment by Yuxin-CV** [comment]
Hi @talent-less, thanks for your interest in our work.

We find it is OK to train `QueryInst-R50` using `2080Ti`. Can you provide your log?

**Comment by talent-less** [comment]
Sorry. I have deleted the logs. 

 Reopen when this happens to someone else.
