### ISSUE TITLE
Learned Proposal Boxes?

### ISSUE THREAD

**Issue by JialianW** [hustvl/QueryInst#16]
I took a look at the self.init_proposal_bboxes.weight from your trained model, but I found the boxes coordinates were not learned and kept around the initial values of 0.5 0.5 1 1. Is there any problem for this? Thanks

**Comment by Yuxin-CV** [comment]
Hi @JialianW, thanks for your valuable issue!

The original Sparse R-CNN use learnable proposal boxes at the first stage, we find detach them produce slightly better object detection results (`0.2~0.3` AP implement). 

You can also check the pre-trained weight provided by the official Sparse R-CNN repo, the learnt proposal boxes at the first stage should be `(~0.5, ~0.5, ~1, ~1)`. That means the proposal boxes at the first stage always trend to `RoIAlign`nearly all the `P4` feature map for every instances, which is somewhat intuitive.

**Comment by JialianW** [comment]
Thank you for the useful answers! I have another question regarding your Youtube-VIS experiments: did you change the roi align mapping threshold for FPN? The default mapping threshold is 56 defined in "class SingleRoIExtractor". Since you use relatively small images for Youtube-VIS, I was wondering if you changed this to make it extract features from higher resolution from FPN?

**Comment by Yuxin-CV** [comment]
> Thank you for the useful answers! I have another question regarding your Youtube-VIS experiments: did you change the roi align mapping threshold for FPN? The default mapping threshold is 56 defined in "class SingleRoIExtractor". Since you use relatively small images for Youtube-VIS, I was wondering if you changed this to make it extract features from higher resolution from FPN?

We haven't changed that :( 
Your suggestion seems quite reasonable and we will try it in the future, thanks!
