### ISSUE TITLE
where can I find the trained models for this repo

### ISSUE THREAD

**Issue by kartikwar** [hustvl/QueryInst#2]
thank you for this amazing work. I wanted to use the trained models for inference. where can I find them?

**Comment by Yuxin-CV** [comment]
Thanks for your interests in our work :)
We will release the model weights in several days, please stay tuned.

**Comment by vealocia** [comment]
@kartikwar Pretrain models are released just now and you can download by the link in README!

**Comment by thangnx183** [comment]
@vealocia , can you upload pre-trained models to google drive ? it seem i cant signup to baidu via my country phone number

**Comment by Yuxin-CV** [comment]
> @vealocia , can you upload pre-trained models to google drive ? it seem i cant signup to baidu via my country phone number

@thangnx183 We are working on it, please stay tuned :)

**Comment by vealocia** [comment]
@thangnx183 We have just added the google drive link, please check the newest README to get them.

**Comment by thangnx183** [comment]
@vealocia thank you so much for quick reply and awesome work
