### ISSUE TITLE
Bias and BN are set at the same time.

### ISSUE THREAD

**Issue by kay-Lifeng** [hustvl/QueryInst#25]
Dear author:
      Why set Bias and BN at the same time in 4 convs after Mask_DynamicConv in QueryInst. When training, the system will launch a warning.

**Comment by vealocia** [comment]
Hi, @kay-Lifeng ! Thanks for your interest in our work and kind comment.
For some reasons,  we use convolutional layers with ```bias=True``` with BatchNorm layer behind in the mask head, while the bias hardly affects the final performance.

**Comment by Yuxin-CV** [comment]
> Dear author:
>       Why set Bias and BN at the same time in 4 convs after Mask_DynamicConv in QueryInst. When training, the system will launch a warning. 

No worry with this warning.

**Comment by kay-Lifeng** [comment]
> > Dear author:
> > Why set Bias and BN at the same time in 4 convs after Mask_DynamicConv in QueryInst. When training, the system will launch a warning.
> 
> No worry with this warning.



> Hi, @kay-Lifeng ! Thanks for your interest in our work and kind comment.
> For some reason, we use convolutional layers with `bias=True` with BatchNorm layer behind in the mask head, while the bias hardly affects the final performance.

Dear author：
When training QueryInst with multi GPUs,  always occur this error， how to deal with it？
subprocess.CalledProcessError: Command '['/opt/conda/envs/zy/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/queryinst/querytrack_config.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by Yuxin-CV** [comment]
Sorry I just deleted your comments by accident, your original comments are:

> When training QueryInst with multi GPUs, always occur this error, how to deal with it？
subprocess.CalledProcessError: Command '['/opt/conda/envs/zy/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/queryinst/querytrack_config.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

It seems you use a different config to train. Can you successfully initiate training with our config?

**Comment by Yuxin-CV** [comment]
I'm closing this issue but let us know if you have any further questions.
