### ISSUE TITLE
How do you handle with the loss_match of track_head in QueryTrack?

### ISSUE THREAD

**Issue by kay-Lifeng** [hustvl/QueryInst#28]
Dear author：
      In MaskTrack, when calculate the loss_match of track_head, the picture having only one instance will not participate in the calculation of loss_mach.  So, if the pictures of one batch all have only one instance, the loss_match of this batch will be 0.  How do you solve this problem in your QueryTrack?

**Comment by Yuxin-CV** [comment]
Please refer to the implantation of Mask Track R-CNN.
