### ISSUE TITLE
"GroundTruth not found"  error

### ISSUE THREAD

**Issue by Colt1990** [hustvl/QueryInst#3]
For the crop augmentation, since the following negative crop setting is alllowed, is anybody meet the "GroundTruth not found" error?  
'allow_negative_crop': True

**Comment by vealocia** [comment]
Actually, "GroundTruth not found" is just a status warning, please refer [this](https://github.com/hustvl/QueryInst/blob/ba00e331120d2eb39b53d39b9b02d27b270e8063/mmdet/models/roi_heads/query_roi_head.py#L194) to see the implementation details. If you find your code get crashed or stuck under such settings, please set "allow_negative_crop" to False.

**Comment by Yuxin-CV** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions.

**Comment by TinyGrass** [comment]
Hi, @Yuxin-CV . I set allow_negative_crop as False, but I still got the "Ground Truth Not Found!" error. What do you suggest?
