### ISSUE TITLE
How to use this with custom Dataset

### ISSUE THREAD

**Issue by jaideep11061982** [hustvl/QueryInst#9]
hi
first of all  thanks for publishing this. May be very basic q
in your Read.md you have provided python command
python tools/train.py configs/queryinst/queryinst_r50_fpn_1x_coco.py

1)I opened it but was not able to understand how does it starts training.
2) How can i use just the model for fine tuning with my custom dataset.

**Comment by vealocia** [comment]
This repo is built upon [mmdetection](https://github.com/open-mmlab/mmdetection) codebase, please refer to the official [instructions](https://mmdetection.readthedocs.io) to use your custom dataset.

**Comment by Yuxin-CV** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions.
